{
 "title": "Perfana JFR Metrics 0.6",
 "description": "Show events from JFR",
 "tags": [
  "jfr",
  "perfana",
  "perfana-template"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": "SHOW TAG VALUES WITH KEY = \"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "SHOW TAG VALUES WITH KEY = \"testEnvironment\" WHERE \"systemUnderTest\" =~ /$system_under_test/"
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\" WHERE \"systemUnderTest\" =~ /$system_under_test/ AND \"testEnvironment\" =~ /$test_environment/"
   },
   {
    "name": "size_bucket",
    "label": "Size bucket",
    "query": "SHOW TAG VALUES FROM \"object-allocation-sample\" WITH KEY = \"size-bucket\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU",
     "query": "SELECT max(*) FROM \"CPU\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT max(*) FROM \"heap\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT max(*) FROM \"threads\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "bytes per second",
     "measurement": "allocation-rate-bytes",
     "query": "SELECT \"bytes\" FROM \"allocation-rate-bytes\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections (young)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "youngGc",
     "query": "SELECT max(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections max (young)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "youngGc",
     "query": "SELECT max(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections total time (young)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "youngGc",
     "query": "SELECT sum(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections (old)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Old GC duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oldGc",
     "query": "SELECT max(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections max (old)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "oldGc",
     "query": "SELECT max(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections total time (old)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "oldGc",
     "query": "SELECT sum(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Safe point duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "safepoint",
     "query": "SELECT max(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe point max",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "safepoint",
     "query": "SELECT distinct(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe point total time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "safepoint",
     "query": "SELECT sum(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Big allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "big allocation size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "big-allocations",
     "query": "SELECT distinct(\"bytes\") FROM \"big-allocations\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Big allocation stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "measurement": "big-allocations",
     "query": "SELECT \"bytes\" FROM \"big-allocations\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "big-allocations",
     "query": "SELECT \"stacktrace\",\"objectClass\" FROM \"big-allocations\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "allocation sample",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "object-allocation-sample",
     "query": "SELECT count(\"bytes\") FROM \"object-allocation-sample\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"size-bucket\" fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Large allocation samples stacktraces",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "measurement": "object-allocation-sample",
       "query": "SELECT \"bytes\" FROM \"object-allocation-sample\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"size-bucket\" =~ /^$size_bucket$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
        { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
       ]
      },
      {
       "measurement": "object-allocation-sample",
       "query": "SELECT \"stacktrace\", \"objectClass\", \"thread\" FROM \"object-allocation-sample\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/ AND \"size-bucket\" =~ /^$size_bucket$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "stacktrace" ], "type": "field" }
        ],
        [
         { "params": [ "objectClass" ], "type": "field" }
        ],
        [
         { "params": [ "thread" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
        { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
        { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Enter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "monitor duration",
     "measurement": "java-monitor-enter",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-enter\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Enter stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "measurement": "java-monitor-enter",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-enter\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "java-monitor-enter",
     "query": "SELECT \"stacktrace\",\"monitor-class\",\"thread\",\"previous-owner\",\"address\" FROM \"java-monitor-enter\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ],
      [
       { "params": [ "address" ], "type": "field" }
      ],
      [
       { "params": [ "monitor-class" ], "type": "field" }
      ],
      [
       { "params": [ "previous-owner" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-wait\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Wait stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-wait\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"stacktrace\",\"monitor-class\",\"thread\",\"notifier\",\"timeout\",\"timed-out\" FROM \"java-monitor-wait\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ],
      [
       { "params": [ "address" ], "type": "field" }
      ],
      [
       { "params": [ "monitor-class" ], "type": "field" }
      ],
      [
       { "params": [ "notifier" ], "type": "field" }
      ],
      [
       { "params": [ "timeout" ], "type": "field" }
      ],
      [
       { "params": [ "timed-out" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Socket read bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host $tag_address $tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "address::tag" ], "type": "tag" }
     ],
     "measurement": "socket-read-rate-bytes",
     "query": "SELECT sum(\"bytes\") FROM \"socket-read-rate-bytes\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"port\"::tag, \"host\"::tag, \"address\"::tag",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Socket write bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host $tag_address $tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "address::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket-write-rate-bytes",
     "query": "SELECT sum(\"bytes\") FROM \"socket-write-rate-bytes\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"port\"::tag, \"address\"::tag, \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "classes-loaded",
     "query": "SELECT max(\"loadedClassCount\") FROM \"classes-loaded\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "loadedClassCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Resident Set Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-resident-set-size",
     "query": "SELECT max(*) FROM \"memory-resident-set-size\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Committed per Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT max(\"committed\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Reserved per Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT max(\"reserved\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval), \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "reserved" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Native Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native-total",
     "query": "SELECT max(*) FROM \"memory-native-total\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread context switch rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "switch rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread-context-switch-rate",
     "query": "SELECT max(\"switchRate\") FROM \"thread-context-switch-rate\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "switchRate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU throttle time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-cpu-throttling-time",
     "query": "SELECT difference(*) FROM \"container-cpu-throttling-time\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU slices",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-cpu-throttling-slices",
     "query": "SELECT difference(*) FROM \"container-cpu-throttling-slices\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-memory-usage",
     "query": "SELECT max(*) FROM \"container-memory-usage\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container memory request failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-memory-usage-failures",
     "query": "SELECT difference(*) FROM \"container-memory-usage-failures\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Threads active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "active virtual threads",
     "query": "SELECT max(\"activeCount\") FROM \"virtual-threads\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Virtual Thread Pinned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "pinned duration",
     "query": "SELECT \"duration-ns\" FROM \"virtual-thread-pinned\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Virtual Thread Pinned stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "alias": "pinned duration",
     "query": "SELECT \"duration-ns\" FROM \"virtual-thread-pinned\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter"
    },
    {
     "alias": "stacktrace",
     "query": "SELECT \"stacktrace\" FROM \"virtual-thread-pinned\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Virtual Thread Submit Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "submit failed",
     "query": "SELECT difference(\"count\") FROM \"virtual-thread-submit-failed\" WHERE (\"service\"::tag =~ /^$service$/ AND \"testEnvironment\"::tag =~ /^$test_environment$/ AND \"systemUnderTest\"::tag =~ /^$system_under_test$/) AND $timeFilter"
    }
   ]
  }
 ]
}